// The six joints covered by the MRC test, in test order. Shared by the /mrc
// start page and the per-test route so both stay in sync.
//
// Everything here is static configuration — it never changes during a test.
// Live values (current angle, repetitions done, …) live in session.ts.
//
// Each joint is written ONCE, for the patient's RIGHT side. The left-side test
// is generated by mirroring the landmarks (see MRC_TESTS at the bottom).

import { POSE, POSE_LANDMARK_NAMES, POSE_MIRROR, PoseLandmarkIndex } from "@/lib/pose/landmarks";

export type MrcJointId = "shoulder" | "elbow" | "wrist" | "hip" | "knee" | "ankle";

export type MrcSide = "right" | "left";

// Angle formed at `vertex` between the lines vertex→points[0] and vertex→points[1].
// Degrees, 0–180.
export type MrcAngleMeasure = {
	kind: "angle";
	vertex: PoseLandmarkIndex;
	points: [PoseLandmarkIndex, PoseLandmarkIndex];
	target: number;
	// Allowed deviation from target (±) that still counts as correct posture.
	tolerance: number;
	// "image" (default): angle as seen in the camera picture — matches what the doctor
	//   sees; place the camera facing the plane of movement.
	// "world": 3D angle using MediaPipe's depth estimate — independent of camera
	//   angle, but depth (z) is noisy and can bend a straight limb by 30°+.
	space?: "image" | "world";
};

// Distance between two landmarks, in centimetres.
export type MrcAlignmentMeasure = {
	kind: "alignment";
	points: [PoseLandmarkIndex, PoseLandmarkIndex];
	target: number;
	tolerance: number;
};

// Tilt of the line points[0]→points[1] against straight down (gravity), in the
// camera picture. Degrees: 0 = hanging down, 90 = horizontal, 180 = straight up.
// Needs only two landmarks — no unstable reference point like the hip — but the
// camera must be level (not tilted).
export type MrcInclinationMeasure = {
	kind: "inclination";
	points: [PoseLandmarkIndex, PoseLandmarkIndex];
	target: number;
	tolerance: number;
};

export type MrcMeasure = MrcAngleMeasure | MrcAlignmentMeasure | MrcInclinationMeasure;

export type MrcJoint = {
	id: MrcJointId;
	name: string;
	region: "Upper limb" | "Lower limb";
	description: string;
	repetitions: number;
	// Sides to test, in order. `measures` are always written for the right side.
	sides: MrcSide[];
	// Where the camera must be (depends on the pose — to be confirmed with the doctor).
	// "front": the patient faces the camera.
	// "side": the TESTED side faces the camera (patient side-on); use only same-side
	//   landmarks, never cross-body pairs like 11↔12 — they overlap in a side view.
	camera: "side" | "front";
	// What the pose model checks during the test (right side). May mix angles and alignments, or be empty.
	measures: MrcMeasure[];
};

export const MRC_JOINTS: MrcJoint[] = [
	{
		id: "shoulder",
		name: "Shoulder",
		region: "Upper limb",
		description: "Shoulder extension.",
		repetitions: 5,
		sides: ["right", "left"],
		camera: "front",
		measures: [
			// Arm straight: angle of right elbow (14), between right wrist (16) and right shoulder (12).
			// A straight line looks straight from any camera angle, so this works side-on.
			{
				kind: "angle",
				vertex: POSE.rightElbow,
				points: [POSE.rightWrist, POSE.rightShoulder],
				target: 180,
				tolerance: 5,
			},
			// Arm horizontal: tilt of the upper arm, right shoulder (12) → right elbow (14), from vertical.
			// Arm hanging down = 0°, horizontal = 90°. (Not the hip: its landmark is unstable.)
			{
				kind: "inclination",
				points: [POSE.rightShoulder, POSE.rightElbow],
				target: 90,
				tolerance: 5,
			},
		],
	},
	// TODO: fill in measures for the remaining joints.
	{
		id: "elbow",
		name: "Elbow",
		region: "Upper limb",
		description: "Assess the elbow joint.",
		repetitions: 5,
		sides: ["right", "left"],
		camera: "side",
		measures: [],
	},
	{
		id: "wrist",
		name: "Wrist",
		region: "Upper limb",
		description: "Assess the wrist joint.",
		repetitions: 5,
		sides: ["right", "left"],
		camera: "side",
		measures: [],
	},
	{
		id: "hip",
		name: "Hip",
		region: "Lower limb",
		description: "Assess the hip joint.",
		repetitions: 5,
		sides: ["right", "left"],
		camera: "side",
		measures: [],
	},
	{
		id: "knee",
		name: "Knee",
		region: "Lower limb",
		description: "Assess the knee joint.",
		repetitions: 5,
		sides: ["right", "left"],
		camera: "side",
		measures: [],
	},
	{
		id: "ankle",
		name: "Ankle",
		region: "Lower limb",
		description: "Assess the ankle joint.",
		repetitions: 5,
		sides: ["right", "left"],
		camera: "side",
		measures: [],
	},
];

export const getMrcJoint = (id: string): MrcJoint | undefined => MRC_JOINTS.find((joint) => joint.id === id);

// The landmark where the measured angle sits (drawn large, with the value label), if any.
export const getMeasureVertex = (measure: MrcMeasure): PoseLandmarkIndex | null =>
	measure.kind === "angle" ? measure.vertex
	: measure.kind === "inclination" ? measure.points[0]
	: null;

// Display name, e.g. "Angle of left shoulder", "Angle of right shoulder (from vertical)"
// or "Alignment of left hip and right hip".
export const getMeasureLabel = (measure: MrcMeasure): string => {
	const name = (i: PoseLandmarkIndex) => POSE_LANDMARK_NAMES[i];
	if (measure.kind === "angle") return `Angle of ${name(measure.vertex)}`;
	if (measure.kind === "inclination") return `Angle of ${name(measure.points[0])} (from vertical)`;
	return `Alignment of ${name(measure.points[0])} and ${name(measure.points[1])}`;
};

// --- Generated per-side tests -------------------------------------------------

// One runnable test: a joint on one side. This is what the test pages and the
// full-test sequence use. Never written by hand — generated from MRC_JOINTS.
export type MrcTest = {
	id: string; // e.g. "shoulder-right"
	joint: MrcJoint;
	side: MrcSide;
	measures: MrcMeasure[];
};

const mirrorMeasure = (measure: MrcMeasure): MrcMeasure => {
	const points: [PoseLandmarkIndex, PoseLandmarkIndex] = [
		POSE_MIRROR[measure.points[0]],
		POSE_MIRROR[measure.points[1]],
	];
	return measure.kind === "angle" ?
			{ ...measure, vertex: POSE_MIRROR[measure.vertex], points }
		:	{ ...measure, points };
};

// All tests in full-test order: each joint's sides in turn (shoulder R, shoulder L, elbow R, …).
export const MRC_TESTS: MrcTest[] = MRC_JOINTS.flatMap((joint) =>
	joint.sides.map((side) => ({
		id: `${joint.id}-${side}`,
		joint,
		side,
		measures: side === "right" ? joint.measures : joint.measures.map(mirrorMeasure),
	}))
);

export const getMrcTest = (id: string): MrcTest | undefined => MRC_TESTS.find((test) => test.id === id);

export const MRC_SIDE_LABEL: Record<MrcSide, string> = { right: "Right", left: "Left" };
