// The six joints covered by the MRC test, in test order. Shared by the /mrc
// start page and the per-test route so both stay in sync.
//
// Everything here is static configuration — it never changes during a test.
// Live values (current angle, repetitions done, …) live in session.ts.
//
// Each joint is written ONCE, for the patient's RIGHT side. The left-side test
// is generated by mirroring the landmarks (see MRC_TESTS at the bottom).

import { POSE, POSE_LANDMARK_NAMES, POSE_MIRROR, PoseLandmarkIndex } from "@/lib/pose/landmarks";

export type MrcJointId = "shoulder" | "elbow" | "wrist" | "hip" | "knee" | "ankle";

export type MrcSide = "right" | "left";

// Angle formed at `vertex` between the lines vertex→points[0] and vertex→points[1].
// Degrees, 0–180.
export type MrcAngleMeasure = {
	kind: "angle";
	vertex: PoseLandmarkIndex;
	points: [PoseLandmarkIndex, PoseLandmarkIndex];
	target: number;
	// Allowed deviation from target (±) that still counts as correct posture.
	tolerance: number;
};

// Distance between two landmarks, in centimetres.
export type MrcAlignmentMeasure = {
	kind: "alignment";
	points: [PoseLandmarkIndex, PoseLandmarkIndex];
	target: number;
	tolerance: number;
};

export type MrcMeasure = MrcAngleMeasure | MrcAlignmentMeasure;

export type MrcJoint = {
	id: MrcJointId;
	name: string;
	region: "Upper limb" | "Lower limb";
	description: string;
	repetitions: number;
	// Sides to test, in order. `measures` are always written for the right side.
	sides: MrcSide[];
	// What the pose model checks during the test (right side). May mix angles and alignments, or be empty.
	measures: MrcMeasure[];
};

export const MRC_JOINTS: MrcJoint[] = [
	{
		id: "shoulder",
		name: "Shoulder",
		region: "Upper limb",
		description: "Shoulder extension.",
		repetitions: 5,
		sides: ["right", "left"],
		measures: [
			// Angle of right shoulder (12), between right elbow (14) and left shoulder (11).
			{
				kind: "angle",
				vertex: POSE.rightShoulder,
				points: [POSE.rightElbow, POSE.leftShoulder],
				target: 180,
				tolerance: 5,
			},
			// Angle of right elbow (14), between right wrist (16) and right shoulder (12).
			{
				kind: "angle",
				vertex: POSE.rightElbow,
				points: [POSE.rightWrist, POSE.rightShoulder],
				target: 180,
				tolerance: 5,
			},
		],
	},
	// TODO: fill in measures for the remaining joints.
	{
		id: "elbow",
		name: "Elbow",
		region: "Upper limb",
		description: "Assess the elbow joint.",
		repetitions: 5,
		sides: ["right", "left"],
		measures: [],
	},
	{
		id: "wrist",
		name: "Wrist",
		region: "Upper limb",
		description: "Assess the wrist joint.",
		repetitions: 5,
		sides: ["right", "left"],
		measures: [],
	},
	{
		id: "hip",
		name: "Hip",
		region: "Lower limb",
		description: "Assess the hip joint.",
		repetitions: 5,
		sides: ["right", "left"],
		measures: [],
	},
	{
		id: "knee",
		name: "Knee",
		region: "Lower limb",
		description: "Assess the knee joint.",
		repetitions: 5,
		sides: ["right", "left"],
		measures: [],
	},
	{
		id: "ankle",
		name: "Ankle",
		region: "Lower limb",
		description: "Assess the ankle joint.",
		repetitions: 5,
		sides: ["right", "left"],
		measures: [],
	},
];

export const getMrcJoint = (id: string): MrcJoint | undefined => MRC_JOINTS.find((joint) => joint.id === id);

// Display name, e.g. "Angle of left shoulder" or "Alignment of left hip and right hip".
export const getMeasureLabel = (measure: MrcMeasure): string =>
	measure.kind === "angle" ?
		`Angle of ${POSE_LANDMARK_NAMES[measure.vertex]}`
	:	`Alignment of ${POSE_LANDMARK_NAMES[measure.points[0]]} and ${POSE_LANDMARK_NAMES[measure.points[1]]}`;

// --- Generated per-side tests -------------------------------------------------

// One runnable test: a joint on one side. This is what the test pages and the
// full-test sequence use. Never written by hand — generated from MRC_JOINTS.
export type MrcTest = {
	id: string; // e.g. "shoulder-right"
	joint: MrcJoint;
	side: MrcSide;
	measures: MrcMeasure[];
};

const mirrorMeasure = (measure: MrcMeasure): MrcMeasure => {
	const points: [PoseLandmarkIndex, PoseLandmarkIndex] = [
		POSE_MIRROR[measure.points[0]],
		POSE_MIRROR[measure.points[1]],
	];
	return measure.kind === "angle" ?
			{ ...measure, vertex: POSE_MIRROR[measure.vertex], points }
		:	{ ...measure, points };
};

// All tests in full-test order: each joint's sides in turn (shoulder R, shoulder L, elbow R, …).
export const MRC_TESTS: MrcTest[] = MRC_JOINTS.flatMap((joint) =>
	joint.sides.map((side) => ({
		id: `${joint.id}-${side}`,
		joint,
		side,
		measures: side === "right" ? joint.measures : joint.measures.map(mirrorMeasure),
	}))
);

export const getMrcTest = (id: string): MrcTest | undefined => MRC_TESTS.find((test) => test.id === id);

export const MRC_SIDE_LABEL: Record<MrcSide, string> = { right: "Right", left: "Left" };
